// downloads.js - Download page functionality

document.addEventListener('DOMContentLoaded', function() {
    loadPurchasedProducts();
});

function loadPurchasedProducts() {
    const purchases = JSON.parse(localStorage.getItem('purchases') || '[]');
    const downloadList = document.getElementById('download-list');
    const noDownloads = document.getElementById('no-downloads');

    if (!downloadList) return;

    const downloadedItems = [];
    purchases.forEach(purchase => {
        purchase.items.forEach(item => {
            downloadedItems.push({
                ...item,
                purchaseDate: purchase.timestamp
            });
        });
    });

    if (downloadedItems.length === 0) {
        downloadList.style.display = 'none';
        if (noDownloads) noDownloads.style.display = 'block';
        return;
    }

    if (noDownloads) noDownloads.style.display = 'none';
    downloadList.style.display = 'grid';

    downloadList.innerHTML = downloadedItems.map(item => `
        <article class="download-item">
            <img src="${item.image}" alt="${item.name}" loading="lazy">
            <div>
                <h3>${item.name}</h3>
                <p>Purchased on: ${new Date(item.purchaseDate).toLocaleDateString()}</p>
                <p>Quantity: ${item.quantity}</p>
            </div>
            <button type="button" class="button" onclick="downloadProduct('${item.name}')">
                <i class="fas fa-download"></i> Download PDF
            </button>
        </article>
    `).join('');
}

function downloadProduct(productName) {
    const placeholder = `Negosyo Plan - ${productName}\n\nThank you for downloading your business blueprint. This is a demo download generated by Negosyo Plan.`;
    const blob = new Blob([placeholder], { type: 'application/pdf' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${productName.toLowerCase().replace(/\s+/g, '_')}_blueprint.pdf`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}

function loadAccountDownloads() {
    const purchases = JSON.parse(localStorage.getItem('purchases') || '[]');
    const accountDownloads = document.getElementById('account-downloads');

    if (!accountDownloads) return;

    const history = [];
    purchases.forEach(purchase => {
        purchase.items.forEach(item => {
            history.push({
                ...item,
                purchaseDate: purchase.timestamp
            });
        });
    });

    if (history.length === 0) {
        accountDownloads.innerHTML = '<p>No downloads available.</p>';
        return;
    }

    accountDownloads.innerHTML = history.map(item => `
        <article class="download-item">
            <h3>${item.name}</h3>
            <p>Purchased: ${new Date(item.purchaseDate).toLocaleDateString()}</p>
            <p>Quantity: ${item.quantity}</p>
            <button type="button" class="button" onclick="downloadProduct('${item.name}')">Download</button>
        </article>
    `).join('');
}
